USE [GD2C2022]
GO

BEGIN TRANSACTION

	DROP TABLE NOT_FOUND.VENTA_PRODUCTO,NOT_FOUND.VENTA_CUPON, NOT_FOUND.CUPON, NOT_FOUND.VENTA_DESCUENTO, NOT_FOUND.VENTA, NOT_FOUND.MEDIO_PAGO,
	NOT_FOUND.TIPO_DESCUENTO, NOT_FOUND.CANAL, NOT_FOUND.MEDIO_ENVIO, NOT_FOUND.CLIENTE, NOT_FOUND.COMPRA_PRODUCTO,
	NOT_FOUND.PRODUCTO_VARIANTE, NOT_FOUND.VARIANTE, NOT_FOUND.TIPO_VARIANTE, NOT_FOUND.PRODUCTO, NOT_FOUND.CATEGORIA, 
	NOT_FOUND.MARCA, NOT_FOUND.MATERIAL, NOT_FOUND.DESCUENTO_COMPRA, NOT_FOUND.COMPRA, NOT_FOUND.PROVEEDOR,
	NOT_FOUND.LOCALIDAD, NOT_FOUND.PROVINCIA

	DROP PROCEDURE NOT_FOUND.migrar_categorias
	DROP PROCEDURE NOT_FOUND.migrar_marcas
	DROP PROCEDURE NOT_FOUND.migrar_materiales
	DROP PROCEDURE NOT_FOUND.migrar_productos
	DROP PROCEDURE NOT_FOUND.migrar_tipos_variante
	DROP PROCEDURE NOT_FOUND.migrar_variantes
	DROP PROCEDURE NOT_FOUND.migrar_productos_variantes
	DROP PROCEDURE NOT_FOUND.migrar_provincias
	DROP PROCEDURE NOT_FOUND.migrar_localidad
	DROP PROCEDURE NOT_FOUND.migrar_clientes
	DROP PROCEDURE NOT_FOUND.migrar_proveedores
	DROP PROCEDURE NOT_FOUND.migrar_medios_pago
	DROP PROCEDURE NOT_FOUND.migrar_compras
	DROP PROCEDURE NOT_FOUND.migrar_canales
	DROP PROCEDURE NOT_FOUND.migrar_medios_envio
	DROP PROCEDURE NOT_FOUND.migrar_compra_descuento
	DROP PROCEDURE NOT_FOUND.migrar_compra_producto
	DROP PROCEDURE NOT_FOUND.migrar_compras_totales
	DROP PROCEDURE NOT_FOUND.migrar_ventas
	DROP PROCEDURE NOT_FOUND.migrar_venta_producto
	DROP PROCEDURE NOT_FOUND.migrar_tipos_descuento
	DROP PROCEDURE NOT_FOUND.migrar_cupones
	DROP PROCEDURE NOT_FOUND.migrar_venta_cupon
	DROP PROCEDURE NOT_FOUND.migrar_venta_descuento
	DROP PROCEDURE NOT_FOUND.migrar_ventas_totales

	DROP PROCEDURE NOT_FOUND.ejecutar_procedures

	DROP SCHEMA NOT_FOUND

COMMIT TRANSACTION
GO