USE [GD2C2022]
GO

----CREACION DE TABLAS---- 

--DIMENSIONES
CREATE TABLE NOT_FOUND.BI_DIMENSION_TIEMPO(
	TIEMPO_ID INT IDENTITY PRIMARY KEY,
	AÑO INT,
	MES INT
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_PROVINCIA(
	PROVINCIA_ID INT PRIMARY KEY,
	PROVINCIA NVARCHAR(255)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_TIPO_DE_ENVIO(
	TIPO_ENVIO_ID INT PRIMARY KEY,
	TIPO_ENVIO NVARCHAR(255)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_MEDIO_DE_PAGO(
	MEDIO_PAGO_ID INT PRIMARY KEY,
	MEDIO_PAGO NVARCHAR(255)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_CANAL_DE_VENTA(
	CANAL_ID INT PRIMARY KEY,
	CANAL NVARCHAR(255),
	COSTO_CANAL DECIMAL(18,2)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_TIPO_DE_DESCUENTO(
	TIPO_DESCUENTO_ID INT PRIMARY KEY,
	TIPO_DESCUENTO NVARCHAR(255)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_RANGO_ETARIO(
	RANGO_ETARIO_ID INT IDENTITY PRIMARY KEY,
	RANGO NVARCHAR(5)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_CATEGORIA(
	CATEGORIA_ID INT PRIMARY KEY,
	CATEGORIA NVARCHAR(255)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_PRODUCTO(
	PRODUCTO_ID NVARCHAR(50) PRIMARY KEY,
	NOMBRE_PRODUCTO NVARCHAR(50),
	DESCRIPCION_PRODUCTO NVARCHAR(50)
)
GO

CREATE TABLE NOT_FOUND.BI_DIMENSION_PROVEEDOR(
	PROVEEDOR_ID NVARCHAR(50) PRIMARY KEY,
	RAZON_SOCIAL NVARCHAR(50),
	DOMICILIO NVARCHAR(50),
	MAIL NVARCHAR(50)
)
GO

---HECHOS
CREATE TABLE NOT_FOUND.BI_HECHOS_VENTAS(
	VENTA_ID DECIMAL(19,0) PRIMARY KEY,
	CANAL_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_CANAL_DE_VENTA,
	MEDIO_PAGO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_MEDIO_DE_PAGO,
	TIPO_ENVIO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIPO_DE_ENVIO,
	PROVINCIA_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_PROVINCIA, 
	TIEMPO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIEMPO,
	TOTAL_VENTA DECIMAL(18,2),
	PRECIO_MEDIO_ENVIO DECIMAL(18,2),
	COSTO_MEDIO_PAGO DECIMAL(18,2),
)
GO

CREATE TABLE NOT_FOUND.BI_HECHOS_DESCUENTOS(
	DESCUENTO_ID INT PRIMARY KEY,
	CANAL_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_CANAL_DE_VENTA,
	TIPO_DESCUENTO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIPO_DE_DESCUENTO,
	MEDIO_PAGO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_MEDIO_DE_PAGO,
	TIEMPO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIEMPO,
	IMPORTE DECIMAL(18,2)
)
GO

CREATE TABLE NOT_FOUND.BI_HECHOS_COMPRAS(
	COMPRA_ID INT PRIMARY KEY,
	PROVEEDOR_ID NVARCHAR(50) REFERENCES NOT_FOUND.BI_DIMENSION_PROVEEDOR,
	PRODUCTO_ID NVARCHAR(50) REFERENCES NOT_FOUND.BI_DIMENSION_PRODUCTO,
	TIEMPO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIEMPO,
	UNIDADES DECIMAL(18,0),
	PRECIO DECIMAL(18,2)
)
GO

CREATE TABLE NOT_FOUND.BI_HECHOS_PRODUCTOS_VENDIDOS(
	PROD_VEND_ID INT PRIMARY KEY,
	RANGO_ETARIO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_RANGO_ETARIO,
	PRODUCTO_ID NVARCHAR(50) REFERENCES NOT_FOUND.BI_DIMENSION_PRODUCTO,
	CATEGORIA_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_CATEGORIA,
	TIEMPO_ID INT REFERENCES NOT_FOUND.BI_DIMENSION_TIEMPO,
	UNIDADES DECIMAL(18,0),
	PRECIO DECIMAL(18,2)
)
GO
------------------------

--CREACION DE VISTAS----
/*
CREATE VIEW NOT_FOUND.BI_GANANCIAS_MES_CANAL AS
	
GO

*/
------------------------

--PROCEDURES MIGRACION TRANSACCIONAL A DIMENSIONAL------


--------------------------------------------------------